---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1
  version: "1.30"

vpc:
  id: "vpc-0b06ba5bfab99498b"
  subnets:
    private:
      us-east-1a: {
        id: "subnet-0422bec13e7eec9e6"
      }
      us-east-1b: {
        id: "subnet-00630bdad3664ee18"
      }
    public:
      us-east-1a: {
        id: "subnet-066a65e68e06df5db"
      }
      us-east-1b: {
        id: "subnet-08ca22e6d15635564"
      }

iam:
  # 为后续 IRSA / Autoscaler 打基础
  withOIDC: true
  # 指向手动建的 Role，权限：AmazonEKSClusterPolicy + AmazonEKSVPCResourceController
  serviceRoleARN: "arn:aws:iam::563149051155:role/eks-admin-role"

managedNodeGroups:
  - name: ng-mixed
    minSize: 0
    desiredCapacity: 3
    maxSize: 6
    # 3 × Spot (Random: t3.small or t3.medium)
    instanceTypes: ["t3.small", "t3.medium"]
    spot: true
    privateNetworking: true
    labels: {
      role: "worker"
    }
    tags:
      project: phase2-sprint
    updateConfig:
      maxUnavailable: 1
    # 可选：限制 Spot 最高价（按需 70%）
    # spotMaxPrice: "0.026"
    subnets:
      - "subnet-0422bec13e7eec9e6"
      - "subnet-00630bdad3664ee18"
