apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1
  version: "1.30"

vpc:
  id: "vpc-0b06ba5bfab99498b"
  subnets:
    private:
      us-east-1a: { id: "subnet-0422bec13e7eec9e6" }
      us-east-1b: { id: "subnet-00630bdad3664ee18" }
    public:
      us-east-1a: { id: "subnet-066a65e68e06df5db" }
      us-east-1b: { id: "subnet-08ca22e6d15635564" }

iam:
  # 为后续 IRSA / Autoscaler 打基础
  withOIDC: true

managedNodeGroups:
  - name: ng-mixed
    minSize: 0
    # Spot (t3.small×2) + OD (t3.medium×1)
    desiredCapacity: 3
    maxSize: 6
    capacityType: SPOT
    # 先抢 spot
    instanceTypes: ["t3.small","t3.medium"]
    spot: true
    privateNetworking: true
    labels: { role: "worker" }
    tags:
      project: phase2-sprint
    updateConfig:
      maxUnavailable: 1
    # 可选：限制 Spot 最高价（按需 70%）
    # spotMaxPrice: "0.026"
    subnets:
      - "subnet-0422bec13e7eec9e6"
      - "subnet-00630bdad3664ee18"

availabilityZones:
  - us-east-1a
  - us-east-1b
