---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        # JSON 格式输出
        args: [--args=-json]
        # 排除子模块目录
        exclude: modules/
      - id: terraform_tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: update-doctoc
        name: Update Doctoc
        entry: scripts/run-doctoc.sh
        language: script
        pass_filenames: false
