---
# 基础运行形态 ---
replicas: 1
image:
  repository: grafana/grafana
  tag: "11.5.0"          # AMP 插件 v2.x 需 Grafana >= 11.5（稳妥起见固定一个 >=11.5 的版本）

service:
  type: ClusterIP
  port: 80

# --- IRSA：让 Helm 创建 SA 并挂上 Role ARN ---
serviceAccount:
  create: true
  name: grafana
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::563149051155:role/grafana-amp-query

# --- 开启 SigV4 支持 & 让 SDK 走默认凭证链（IRSA） ---
env:
  AWS_SDK_LOAD_CONFIG: "true"
  GF_AUTH_SIGV4_AUTH_ENABLED: "true"

# --- 安装 AMP 数据源插件 ---
plugins:
  - grafana-amazonprometheus-datasource

# --- 以 provisioning 方式声明数据源（默认指向 AMP） ---
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: AMP
        # 使用 AMP 专用类型
        type: grafana-amazonprometheus-datasource
        isDefault: true
        access: proxy
        url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-4c9b04d5-5e49-415e-90ef-747450304dca  # yamllint disable-line rule:line-length
        jsonData:
          authType: default               # 使用 AWS SDK 默认链（IRSA）
          defaultRegion: us-east-1
          httpMethod: POST
          # 添加显式配置（直接使用 Pod 角色，无需再 AssumeRole）
          sigV4Auth: true
          sigV4AuthType: default
          sigV4Region: us-east-1
        editable: false

# --- 预置 Dashboard ---
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
# 该仪表盘提供 Task API 在 Amazon Managed Prometheus 中的核心运行指标，
# 默认时间范围为过去 1 小时，每 30 秒刷新一次。
dashboards:
  default:
    task-api-observability:
      # 这里的 JSON 会被 Helm 写成 ConfigMap 并挂载到上面声明的目录，Grafana 启动时自动读取。
      # 面板未显式指定数据源时会使用默认数据源（已把 AMP 设为 isDefault: true，因此可直接生效）。
      # 仪表盘 变量 app 用 label_values(..., application) 自动取值。
      # 三个面板都未写 datasource 字段，Grafana 会使用默认数据源（即 Provision 的 AMP）。
      # 仪表盘布局是 24 列栅格：三块各 8 列并排。
      file: dashboards/task-api-observability.json

# --- 管理员账号（临时密码，登陆后请改） ---
adminUser: admin
adminPassword: "password"

# --- 资源略收敛即可 ---
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {cpu: 200m, memory: 256Mi}
