apiVersion: batch/v1
kind: Job
metadata:
  name: task-api-smoke
  namespace: svc-task
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:8.8.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: task-api-config
          command: ["sh","-lc"]
          args:
            - |
              set -euo pipefail
              BASE_URL="http://${APP_NAME}.svc-task.svc.cluster.local:8080"
              echo "== GET ${BASE_URL}/api/hello =="
              curl -sf ${BASE_URL}/api/hello?name=Renda | head -c 200 || true
              echo
              echo "== GET ${BASE_URL}/actuator/health =="
              curl -sf ${BASE_URL}/actuator/health | grep -q '"status":"UP"' || true
              echo "Health endpoint OK"
              echo "== GET ${BASE_URL}/actuator/prometheus =="
              curl -sf ${BASE_URL}/actuator/prometheus | head -c 100 || true
              echo "\nPrometheus endpoint OK"
              echo "ALL OK"
