---
# Namespace 与 ServiceAccount 定义
apiVersion: v1
kind: Namespace
metadata:
  name: svc-task
  labels:
    app.kubernetes.io/part-of: task-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-api
  namespace: svc-task
  labels:
    app.kubernetes.io/name: task-api
# IRSA 注解由 scripts/lifecycle/post-recreate.sh 的 ensure_task_api_service_account 动态写入
# 若要改为通过 YAML 静态声明，请先移除脚本中的注入逻辑，并取消下列注释填入对应 role-arn
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
